/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DenunciaAnonimaRouteImport } from './routes/denuncia-anonima'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DenunciaIdRouteImport } from './routes/denuncia.$id'
import { Route as AuthenticatedPainelFiscalRouteImport } from './routes/_authenticated/painel-fiscal'
import { Route as AuthenticatedNovaDenunciaRouteImport } from './routes/_authenticated/nova-denuncia'
import { Route as AuthenticatedMinhasDenunciasRouteImport } from './routes/_authenticated/minhas-denuncias'
import { Route as AuthenticatedGuardaMorenoRouteImport } from './routes/_authenticated/guarda-moreno'
import { Route as ApiPublicAnonymousEvidenceRouteImport } from './routes/api/public/anonymous-evidence'

const DenunciaAnonimaRoute = DenunciaAnonimaRouteImport.update({
  id: '/denuncia-anonima',
  path: '/denuncia-anonima',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciaIdRoute = DenunciaIdRouteImport.update({
  id: '/denuncia/$id',
  path: '/denuncia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelFiscalRoute =
  AuthenticatedPainelFiscalRouteImport.update({
    id: '/painel-fiscal',
    path: '/painel-fiscal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNovaDenunciaRoute =
  AuthenticatedNovaDenunciaRouteImport.update({
    id: '/nova-denuncia',
    path: '/nova-denuncia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinhasDenunciasRoute =
  AuthenticatedMinhasDenunciasRouteImport.update({
    id: '/minhas-denuncias',
    path: '/minhas-denuncias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuardaMorenoRoute =
  AuthenticatedGuardaMorenoRouteImport.update({
    id: '/guarda-moreno',
    path: '/guarda-moreno',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicAnonymousEvidenceRoute =
  ApiPublicAnonymousEvidenceRouteImport.update({
    id: '/api/public/anonymous-evidence',
    path: '/api/public/anonymous-evidence',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/denuncia-anonima': typeof DenunciaAnonimaRoute
  '/guarda-moreno': typeof AuthenticatedGuardaMorenoRoute
  '/minhas-denuncias': typeof AuthenticatedMinhasDenunciasRoute
  '/nova-denuncia': typeof AuthenticatedNovaDenunciaRoute
  '/painel-fiscal': typeof AuthenticatedPainelFiscalRoute
  '/denuncia/$id': typeof DenunciaIdRoute
  '/api/public/anonymous-evidence': typeof ApiPublicAnonymousEvidenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/denuncia-anonima': typeof DenunciaAnonimaRoute
  '/guarda-moreno': typeof AuthenticatedGuardaMorenoRoute
  '/minhas-denuncias': typeof AuthenticatedMinhasDenunciasRoute
  '/nova-denuncia': typeof AuthenticatedNovaDenunciaRoute
  '/painel-fiscal': typeof AuthenticatedPainelFiscalRoute
  '/denuncia/$id': typeof DenunciaIdRoute
  '/api/public/anonymous-evidence': typeof ApiPublicAnonymousEvidenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/denuncia-anonima': typeof DenunciaAnonimaRoute
  '/_authenticated/guarda-moreno': typeof AuthenticatedGuardaMorenoRoute
  '/_authenticated/minhas-denuncias': typeof AuthenticatedMinhasDenunciasRoute
  '/_authenticated/nova-denuncia': typeof AuthenticatedNovaDenunciaRoute
  '/_authenticated/painel-fiscal': typeof AuthenticatedPainelFiscalRoute
  '/denuncia/$id': typeof DenunciaIdRoute
  '/api/public/anonymous-evidence': typeof ApiPublicAnonymousEvidenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/denuncia-anonima'
    | '/guarda-moreno'
    | '/minhas-denuncias'
    | '/nova-denuncia'
    | '/painel-fiscal'
    | '/denuncia/$id'
    | '/api/public/anonymous-evidence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/denuncia-anonima'
    | '/guarda-moreno'
    | '/minhas-denuncias'
    | '/nova-denuncia'
    | '/painel-fiscal'
    | '/denuncia/$id'
    | '/api/public/anonymous-evidence'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/denuncia-anonima'
    | '/_authenticated/guarda-moreno'
    | '/_authenticated/minhas-denuncias'
    | '/_authenticated/nova-denuncia'
    | '/_authenticated/painel-fiscal'
    | '/denuncia/$id'
    | '/api/public/anonymous-evidence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DenunciaAnonimaRoute: typeof DenunciaAnonimaRoute
  DenunciaIdRoute: typeof DenunciaIdRoute
  ApiPublicAnonymousEvidenceRoute: typeof ApiPublicAnonymousEvidenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/denuncia-anonima': {
      id: '/denuncia-anonima'
      path: '/denuncia-anonima'
      fullPath: '/denuncia-anonima'
      preLoaderRoute: typeof DenunciaAnonimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denuncia/$id': {
      id: '/denuncia/$id'
      path: '/denuncia/$id'
      fullPath: '/denuncia/$id'
      preLoaderRoute: typeof DenunciaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel-fiscal': {
      id: '/_authenticated/painel-fiscal'
      path: '/painel-fiscal'
      fullPath: '/painel-fiscal'
      preLoaderRoute: typeof AuthenticatedPainelFiscalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nova-denuncia': {
      id: '/_authenticated/nova-denuncia'
      path: '/nova-denuncia'
      fullPath: '/nova-denuncia'
      preLoaderRoute: typeof AuthenticatedNovaDenunciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minhas-denuncias': {
      id: '/_authenticated/minhas-denuncias'
      path: '/minhas-denuncias'
      fullPath: '/minhas-denuncias'
      preLoaderRoute: typeof AuthenticatedMinhasDenunciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guarda-moreno': {
      id: '/_authenticated/guarda-moreno'
      path: '/guarda-moreno'
      fullPath: '/guarda-moreno'
      preLoaderRoute: typeof AuthenticatedGuardaMorenoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/anonymous-evidence': {
      id: '/api/public/anonymous-evidence'
      path: '/api/public/anonymous-evidence'
      fullPath: '/api/public/anonymous-evidence'
      preLoaderRoute: typeof ApiPublicAnonymousEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedGuardaMorenoRoute: typeof AuthenticatedGuardaMorenoRoute
  AuthenticatedMinhasDenunciasRoute: typeof AuthenticatedMinhasDenunciasRoute
  AuthenticatedNovaDenunciaRoute: typeof AuthenticatedNovaDenunciaRoute
  AuthenticatedPainelFiscalRoute: typeof AuthenticatedPainelFiscalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGuardaMorenoRoute: AuthenticatedGuardaMorenoRoute,
  AuthenticatedMinhasDenunciasRoute: AuthenticatedMinhasDenunciasRoute,
  AuthenticatedNovaDenunciaRoute: AuthenticatedNovaDenunciaRoute,
  AuthenticatedPainelFiscalRoute: AuthenticatedPainelFiscalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DenunciaAnonimaRoute: DenunciaAnonimaRoute,
  DenunciaIdRoute: DenunciaIdRoute,
  ApiPublicAnonymousEvidenceRoute: ApiPublicAnonymousEvidenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
